### ISSUE TITLE
Random release not found errors

### ISSUE THREAD

**Issue by sagikazarmark** [hashicorp/terraform-provider-helm#25]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.10.4

### Affected Resource(s)
Please list the resources as a list, for example:
- helm_chart

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "kubernetes_namespace" "metrics" {
    metadata {
        name = "metrics"
    }
}

resource "helm_chart" "prometheus" {
    name       = "prometheus"
    namespace  = "${kubernetes_namespace.metrics.metadata.0.name}"
    chart      = "prometheus"
    repository = "stable"
    version    = "4.5.0"

    set {
        name  = "rbac.create"
        value = true
    }
}

```

Happens with several different configurations as well

### Debug Output
Running terraform for a day with `TF_LOG=TRACE` and simply can't reproduce the error. Then later this day I forgot to put the option before the command, and it happened again. That's when I decided to open this issue.

### Panic Output
None

### Expected Behavior
Terraform should just work

### Actual Behavior
Terraform fails with `helm_chart.prometheus: release not found`. While the release is definitely there.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` or `terraform plan`

### Important Factoids
Running Helm 2.6.1 with the same Tiller version.

**Comment by sagikazarmark** [comment]
Not sure if it's much of help, but:

```
2017/09/21 19:11:47 [TRACE] dag/walk: vertex "provider.helm (close)", waiting for: "module.dev-k8s.helm_chart.prometheus"
2017/09/21 19:11:47 [ERROR] root.dev-k8s: eval: *terraform.EvalRefresh, err: helm_chart.prometheus: release not found
2017/09/21 19:11:47 [ERROR] root.dev-k8s: eval: *terraform.EvalSequence, err: helm_chart.prometheus: release not found
2017/09/21 19:11:47 [TRACE] [walkRefresh] Exiting eval tree: module.dev-k8s.helm_chart.prometheus
```

**Comment by sagikazarmark** [comment]
Similarly random errors: `helm_chart.prometheus: unexpected EOF`

**Comment by Stelminator** [comment]
I see this quite often, too.

**Comment by madmod** [comment]
I have been able to work around this issue by running Terraform with —parallelism=1. After doing that I am able to consistently deploy multiple helm_chart resources at once without issue. (Other than being slow.) Hopefully that helps someone diagnose the issue.

**Comment by Stelminator** [comment]
I have a suspicion this is related to https://github.com/mcuadros/terraform-provider-helm/issues/20 and https://github.com/mcuadros/terraform-provider-helm/commit/c59546799ff8895223e6826a5c1609c7a63b65ad

**Comment by rporres** [comment]
Taking a look into this, I've found a fatal error

```
fatal error: concurrent map writes
```

As plugins are run as a separate process communicating through an RPC interface, the panic of the plugin process could explain the `EOF` errors  

Complete error stack

```
2017-12-04T19:53:58.229+0100 [DEBUG] plugin.terraform-provider-helm: fatal error: concurrent map writes
2017-12-04T19:53:58.233+0100 [DEBUG] plugin.terraform-provider-helm:
2017-12-04T19:53:58.233+0100 [DEBUG] plugin.terraform-provider-helm: goroutine 24 [running]:
2017-12-04T19:53:58.233+0100 [DEBUG] plugin.terraform-provider-helm: runtime.throw(0x2d64dcd, 0x15)
2017-12-04T19:53:58.233+0100 [DEBUG] plugin.terraform-provider-helm:    /home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/panic.go:605 +0x95 fp=0xc4208731e0 sp=0xc4208731c0 pc=0x102a715
2017-12-04T19:53:58.233+0100 [DEBUG] plugin.terraform-provider-helm: runtime.mapassign_faststr(0x2ac6660, 0xc420828480, 0x2d59513, 0xc, 0xc420816c30)
2017-12-04T19:53:58.233+0100 [DEBUG] plugin.terraform-provider-helm:    /home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/hashmap_fast.go:685 +0x4da fp=0xc420873260 sp=0xc4208731e0 pc=0x100cb4a
2017-12-04T19:53:58.233+0100 [DEBUG] plugin.terraform-provider-helm: github.com/mcuadros/terraform-provider-helm/vendor/github.com/hashicorp/terraform/helper/schema.(*DiffFieldReader).ReadField(0xc420828420, 0xc42049a390, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4208735f8, ...)
2017-12-04T19:53:58.233+0100 [DEBUG] plugin.terraform-provider-helm:    /home/travis/gopath/src/github.com/mcuadros/terraform-provider-helm/vendor/github.com/hashicorp/terraform/helper/schema/field_reader_diff.go:80 +0x3a6 fp=0xc4208734c0 sp=0xc420873260 pc=0x16a1976
2017-12-04T19:53:58.233+0100 [DEBUG] plugin.terraform-provider-helm: github.com/mcuadros/terraform-provider-helm/vendor/github.com/hashicorp/terraform/helper/schema.(*MultiLevelFieldReader).ReadFieldMerge(0xc420544aa0, 0xc42049a390, 0x1, 0x1, 0x2d4ee09, 0x3, 0x0, 0x0, 0x0, 0x0, ...)
2017-12-04T19:53:58.233+0100 [DEBUG] plugin.terraform-provider-helm:    /home/travis/gopath/src/github.com/mcuadros/terraform-provider-helm/vendor/github.com/hashicorp/terraform/helper/schema/field_reader_multi.go:45 +0x260 fp=0xc420873608 sp=0xc4208734c0 pc=0x16a5890
2017-12-04T19:53:58.233+0100 [DEBUG] plugin.terraform-provider-helm: github.com/mcuadros/terraform-provider-helm/vendor/github.com/hashicorp/terraform/helper/schema.(*ResourceData).get(0xc42034c070, 0xc42049a390, 0x1, 0x1, 0xc42049a308, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2017-12-04T19:53:58.233+0100 [DEBUG] plugin.terraform-provider-helm:    /home/travis/gopath/src/github.com/mcuadros/terraform-provider-helm/vendor/github.com/hashicorp/terraform/helper/schema/resource_data.go:493 +0x3ed fp=0xc420873740 sp=0xc420873608 pc=0x16b0dad
2017-12-04T19:53:58.233+0100 [DEBUG] plugin.terraform-provider-helm: github.com/mcuadros/terraform-provider-helm/vendor/github.com/hashicorp/terraform/helper/schema.(*ResourceData).getRaw(0xc42034c070, 0x2d59513, 0xc, 0x2f06e08, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
2017-12-04T19:53:58.233+0100 [DEBUG] plugin.terraform-provider-helm:    /home/travis/gopath/src/github.com/mcuadros/terraform-provider-helm/vendor/github.com/hashicorp/terraform/helper/schema/resource_data.go:129 +0x95 fp=0xc4208737d8 sp=0xc420873740 pc=0x16ae785
2017-12-04T19:53:58.233+0100 [DEBUG] plugin.terraform-provider-helm: github.com/mcuadros/terraform-provider-helm/vendor/github.com/hashicorp/terraform/helper/schema.(*ResourceData).GetOk(0xc42034c070, 0x2d59513, 0xc, 0x29fb100, 0xc420815fd0, 0xc4205ac401)
2017-12-04T19:53:58.233+0100 [DEBUG] plugin.terraform-provider-helm:    /home/travis/gopath/src/github.com/mcuadros/terraform-provider-helm/vendor/github.com/hashicorp/terraform/helper/schema/resource_data.go:90 +0x5f fp=0xc420873888 sp=0xc4208737d8 pc=0x16ae4bf
2017-12-04T19:53:58.233+0100 [DEBUG] plugin.terraform-provider-helm: github.com/mcuadros/terraform-provider-helm/vendor/github.com/hashicorp/terraform/helper/schema.(*ResourceData).Get(0xc42034c070, 0x2d59513, 0xc, 0x29fb100, 0xc420815fd0)
2017-12-04T19:53:58.233+0100 [DEBUG] plugin.terraform-provider-helm:    /home/travis/gopath/src/github.com/mcuadros/terraform-provider-helm/vendor/github.com/hashicorp/terraform/helper/schema/resource_data.go:69 +0x3f fp=0xc4208738c8 sp=0xc420873888 pc=0x16ae29f
2017-12-04T19:53:58.233+0100 [DEBUG] plugin.terraform-provider-helm: github.com/mcuadros/terraform-provider-helm/helm.(*Meta).installTillerIfNeeded(0xc420801c20, 0xc42034c070, 0xc4205ac3f0, 0x46fbf78)
2017-12-04T19:53:58.233+0100 [DEBUG] plugin.terraform-provider-helm:    /home/travis/gopath/src/github.com/mcuadros/terraform-provider-helm/helm/provider.go:315 +0xc1 fp=0xc420873938 sp=0xc4208738c8 pc=0x28d6421
2017-12-04T19:53:58.233+0100 [DEBUG] plugin.terraform-provider-helm: github.com/mcuadros/terraform-provider-helm/helm.(*Meta).connect(0xc420801c20, 0x46926c8, 0x0)
2017-12-04T19:53:58.233+0100 [DEBUG] plugin.terraform-provider-helm:    /home/travis/gopath/src/github.com/mcuadros/terraform-provider-helm/helm/provider.go:215 +0x38 fp=0xc420873968 sp=0xc420873938 pc=0x28d5268
2017-12-04T19:53:58.233+0100 [DEBUG] plugin.terraform-provider-helm: github.com/mcuadros/terraform-provider-helm/helm.(*Meta).GetHelmClient(0xc420801c20, 0x0, 0xc42078b9d0, 0x1010eb8, 0x70)
2017-12-04T19:53:58.233+0100 [DEBUG] plugin.terraform-provider-helm:    /home/travis/gopath/src/github.com/mcuadros/terraform-provider-helm/helm/provider.go:206 +0x66 fp=0xc420873990 sp=0xc420873968 pc=0x28d51e6
2017-12-04T19:53:58.233+0100 [DEBUG] plugin.terraform-provider-helm: github.com/mcuadros/terraform-provider-helm/helm.resourceChartExists(0xc4205ac3f0, 0x2bfb000, 0xc420801c20, 0x24, 0x3ec5340, 0x0)
2017-12-04T19:53:58.233+0100 [DEBUG] plugin.terraform-provider-helm:    /home/travis/gopath/src/github.com/mcuadros/terraform-provider-helm/helm/resource_chart.go:302 +0x44 fp=0xc4208739e0 sp=0xc420873990 pc=0x28da744
2017-12-04T19:53:58.233+0100 [DEBUG] plugin.terraform-provider-helm: github.com/mcuadros/terraform-provider-helm/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc420801440, 0xc42033c1e0, 0x2bfb000, 0xc420801c20, 0xc4201cfdc8, 0xc42074bf01, 0x80000000018)
2017-12-04T19:53:58.233+0100 [DEBUG] plugin.terraform-provider-helm:    /home/travis/gopath/src/github.com/mcuadros/terraform-provider-helm/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:298 +0x3bf fp=0xc420873a88 sp=0xc4208739e0 pc=0x16ad0bf
2017-12-04T19:53:58.233+0100 [DEBUG] plugin.terraform-provider-helm: github.com/mcuadros/terraform-provider-helm/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc4201bf570, 0xc42033c190, 0xc42033c1e0, 0x46926c8, 0x0, 0x18)
2017-12-04T19:53:58.233+0100 [DEBUG] plugin.terraform-provider-helm:    /home/travis/gopath/src/github.com/mcuadros/terraform-provider-helm/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:284 +0x9a fp=0xc420873ae0 sp=0xc420873a88 pc=0x16aac0a
2017-12-04T19:53:58.233+0100 [DEBUG] plugin.terraform-provider-helm: github.com/mcuadros/terraform-provider-helm/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc42045fa00, 0xc42049a280, 0xc42049a350, 0x0, 0x0)
2017-12-04T19:53:58.233+0100 [DEBUG] plugin.terraform-provider-helm:    /home/travis/gopath/src/github.com/mcuadros/terraform-provider-helm/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:510 +0x4e fp=0xc420873b38 sp=0xc420873ae0 pc=0x1696eee
2017-12-04T19:53:58.233+0100 [DEBUG] plugin.terraform-provider-helm: runtime.call64(0xc42074bf20, 0xc42000cdb8, 0xc4206b0510, 0x1800000028)
2017-12-04T19:53:58.233+0100 [DEBUG] plugin.terraform-provider-helm:    /home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/asm_amd64.s:510 +0x3b fp=0xc420873b88 sp=0xc420873b38 pc=0x1055b2b
2017-12-04T19:53:58.233+0100 [DEBUG] plugin.terraform-provider-helm: reflect.Value.call(0xc42076cd20, 0xc42000cdb8, 0x13, 0x2d4f14b, 0x4, 0xc42078bf20, 0x3, 0x3, 0x0, 0x0, ...)
2017-12-04T19:53:58.233+0100 [DEBUG] plugin.terraform-provider-helm:    /home/travis/.gimme/versions/go1.9.linux.amd64/src/reflect/value.go:434 +0x906 fp=0xc420873e60 sp=0xc420873b88 pc=0x10ba516
2017-12-04T19:53:58.233+0100 [DEBUG] plugin.terraform-provider-helm: reflect.Value.Call(0xc42076cd20, 0xc42000cdb8, 0x13, 0xc42002cf20, 0x3, 0x3, 0x0, 0x0, 0x0)
2017-12-04T19:53:58.233+0100 [DEBUG] plugin.terraform-provider-helm:    /home/travis/.gimme/versions/go1.9.linux.amd64/src/reflect/value.go:302 +0xa4 fp=0xc420873ec8 sp=0xc420873e60 pc=0x10b9af4
2017-12-04T19:53:58.233+0100 [DEBUG] plugin.terraform-provider-helm: net/rpc.(*service).call(0xc4207e1780, 0xc42049d8b0, 0xc4202b6da0, 0xc420447080, 0xc42045fac0, 0x29994a0, 0xc42049a280, 0x16, 0x29994e0, 0xc42049a350, ...)
2017-12-04T19:53:58.233+0100 [DEBUG] plugin.terraform-provider-helm:    /home/travis/.gimme/versions/go1.9.linux.amd64/src/net/rpc/server.go:381 +0x142 fp=0xc420873f78 sp=0xc420873ec8 pc=0x13e4a52
2017-12-04T19:53:58.233+0100 [DEBUG] plugin.terraform-provider-helm: runtime.goexit()
2017-12-04T19:53:58.233+0100 [DEBUG] plugin.terraform-provider-helm:    /home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc420873f80 sp=0xc420873f78 pc=0x10582a1
2017-12-04T19:53:58.233+0100 [DEBUG] plugin.terraform-provider-helm: created by net/rpc.(*Server).ServeCodec
2017-12-04T19:53:58.233+0100 [DEBUG] plugin.terraform-provider-helm:    /home/travis/.gimme/versions/go1.9.linux.amd64/src/net/rpc/server.go:475 +0x36b
```

**Comment by rporres** [comment]
I've been able to get rid of the `concurrent map writes` error by adding `mutex` field before the `data` field of the `Meta` struct in [provider.go](helm/provider.go) and locking inside the `installTillerIfNeeded` but I still get random `release not found` errors so I guess they're different things. Created new issue for that https://github.com/mcuadros/terraform-provider-helm/issues/33

**Comment by caarlos0** [comment]
not sure if it is the same error, but I still get random EOFs here.

The thing that's different is that helm provider is used a terraform module, and I have a `main.tf` using that module several times, one for each cluster (I basically apply the same thing to several clusters)... maybe another concurrent thing? 

I don't remember being able to reproduce this issue running against a single cluster at a time...
