### ISSUE TITLE
Terraform crashed when upgraded from Helm2 to Helm3

### ISSUE THREAD

**Issue by gau1991** [hashicorp/terraform-provider-helm#423]
Terraform crashed when upgraded from Helm2 to Helm3 and provider version is updated to latest

### Terraform Version
```
$ terraform version
Terraform v0.12.19
```

### Affected Resource(s)
- helm_release
- helm_repository

### Panic Output
```
panic: runtime error: invalid memory address or nil pointer dereference
2020-02-26T15:40:09.571+0530 [DEBUG] plugin.terraform-provider-helm_v1.0.0_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0x24855cc]
2020-02-26T15:40:09.571+0530 [DEBUG] plugin.terraform-provider-helm_v1.0.0_x4:
2020-02-26T15:40:09.571+0530 [DEBUG] plugin.terraform-provider-helm_v1.0.0_x4: goroutine 119 [running]:
2020-02-26T15:40:09.571+0530 [DEBUG] plugin.terraform-provider-helm_v1.0.0_x4: helm.sh/helm/v3/pkg/chart/loader.LoadFiles(0xc0007b2100, 0x1f, 0x20, 0x1f, 0x20, 0x0)
2020-02-26T15:40:09.571+0530 [DEBUG] plugin.terraform-provider-helm_v1.0.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-helm/vendor/helm.sh/helm/v3/pkg/chart/loader/load.go:126 +0xa9c
2020-02-26T15:40:09.571+0530 [DEBUG] plugin.terraform-provider-helm_v1.0.0_x4: helm.sh/helm/v3/pkg/chart/loader.LoadArchive(0x2ece380, 0xc00050a110, 0xc00050a110, 0x0, 0x0)
2020-02-26T15:40:09.571+0530 [DEBUG] plugin.terraform-provider-helm_v1.0.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-helm/vendor/helm.sh/helm/v3/pkg/chart/loader/archive.go:193 +0x87
2020-02-26T15:40:09.571+0530 [DEBUG] plugin.terraform-provider-helm_v1.0.0_x4: helm.sh/helm/v3/pkg/chart/loader.LoadFile(0xc000040b40, 0x43, 0x0, 0x0, 0x0)
2020-02-26T15:40:09.571+0530 [DEBUG] plugin.terraform-provider-helm_v1.0.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-helm/vendor/helm.sh/helm/v3/pkg/chart/loader/archive.go:65 +0x221
2020-02-26T15:40:09.571+0530 [DEBUG] plugin.terraform-provider-helm_v1.0.0_x4: helm.sh/helm/v3/pkg/chart/loader.FileLoader.Load(...)
2020-02-26T15:40:09.571+0530 [DEBUG] plugin.terraform-provider-helm_v1.0.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-helm/vendor/helm.sh/helm/v3/pkg/chart/loader/archive.go:43
2020-02-26T15:40:09.571+0530 [DEBUG] plugin.terraform-provider-helm_v1.0.0_x4: helm.sh/helm/v3/pkg/chart/loader.Load(0xc000040b40, 0x43, 0x11, 0xc0005268c0, 0xc000040b40)
2020-02-26T15:40:09.571+0530 [DEBUG] plugin.terraform-provider-helm_v1.0.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-helm/vendor/helm.sh/helm/v3/pkg/chart/loader/load.go:62 +0x79
2020-02-26T15:40:09.571+0530 [DEBUG] plugin.terraform-provider-helm_v1.0.0_x4: github.com/terraform-providers/terraform-provider-helm/helm.getChart(0x2ecbde0, 0xc000987ec0, 0xc0002bcdb0, 0xc000755980, 0x11, 0xc00037d9e0, 0x0, 0x0, 0x0, 0x0, ...)
2020-02-26T15:40:09.571+0530 [DEBUG] plugin.terraform-provider-helm_v1.0.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-helm/helm/resource_release.go:622 +0x117
2020-02-26T15:40:09.571+0530 [DEBUG] plugin.terraform-provider-helm_v1.0.0_x4: github.com/terraform-providers/terraform-provider-helm/helm.resourceDiff(0xc000987ec0, 0x2930580, 0xc0002bcdb0, 0xc000481a00, 0xc000987ec0)
2020-02-26T15:40:09.571+0530 [DEBUG] plugin.terraform-provider-helm_v1.0.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-helm/helm/resource_release.go:525 +0x114
2020-02-26T15:40:09.571+0530 [DEBUG] plugin.terraform-provider-helm_v1.0.0_x4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.schemaMap.Diff(0xc00024e420, 0xc0000b9310, 0xc0009894d0, 0x2c05e00, 0x2930580, 0xc0002bcdb0, 0x2f1a800, 0xc0008907c8, 0xffffffffffffffff, 0x0)
2020-02-26T15:40:09.571+0530 [DEBUG] plugin.terraform-provider-helm_v1.0.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-helm/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/schema.go:509 +0xac2
2020-02-26T15:40:09.571+0530 [DEBUG] plugin.terraform-provider-helm_v1.0.0_x4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).simpleDiff(0xc0003c9d00, 0xc0000b9310, 0xc0009894d0, 0x2930580, 0xc0002bcdb0, 0xc000989401, 0x0, 0x0)
2020-02-26T15:40:09.571+0530 [DEBUG] plugin.terraform-provider-helm_v1.0.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-helm/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:351 +0x85
2020-02-26T15:40:09.571+0530 [DEBUG] plugin.terraform-provider-helm_v1.0.0_x4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).SimpleDiff(0xc000404f00, 0xc0001d1978, 0xc0000b9310, 0xc0009894d0, 0xc0008aea90, 0xc0009894d0, 0x0)
2020-02-26T15:40:09.571+0530 [DEBUG] plugin.terraform-provider-helm_v1.0.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-helm/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/provider.go:321 +0x99
2020-02-26T15:40:09.571+0530 [DEBUG] plugin.terraform-provider-helm_v1.0.0_x4: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).PlanResourceChange(0xc000126740, 0x2f191a0, 0xc000aac2a0, 0xc000933140, 0xc000126740, 0xc000aac2a0, 0xc000847a80)
2020-02-26T15:40:09.571+0530 [DEBUG] plugin.terraform-provider-helm_v1.0.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-helm/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:633 +0x765
2020-02-26T15:40:09.571+0530 [DEBUG] plugin.terraform-provider-helm_v1.0.0_x4: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_PlanResourceChange_Handler(0x2a92ce0, 0xc000126740, 0x2f191a0, 0xc000aac2a0, 0xc0009330e0, 0x0, 0x2f191a0, 0xc000aac2a0, 0xc0008dc000, 0x1ab1)
2020-02-26T15:40:09.571+0530 [DEBUG] plugin.terraform-provider-helm_v1.0.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-helm/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3171 +0x217
2020-02-26T15:40:09.571+0530 [DEBUG] plugin.terraform-provider-helm_v1.0.0_x4: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00039c160, 0x2f3fe00, 0xc000557500, 0xc00081fc00, 0xc0006a2e70, 0x3ee3b88, 0x0, 0x0, 0x0)
2020-02-26T15:40:09.571+0530 [DEBUG] plugin.terraform-provider-helm_v1.0.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-helm/vendor/google.golang.org/grpc/server.go:995 +0x460
2020-02-26T15:40:09.571+0530 [DEBUG] plugin.terraform-provider-helm_v1.0.0_x4: google.golang.org/grpc.(*Server).handleStream(0xc00039c160, 0x2f3fe00, 0xc000557500, 0xc00081fc00, 0x0)
2020-02-26T15:40:09.571+0530 [DEBUG] plugin.terraform-provider-helm_v1.0.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-helm/vendor/google.golang.org/grpc/server.go:1275 +0xd97
2020-02-26T15:40:09.572+0530 [DEBUG] plugin.terraform-provider-helm_v1.0.0_x4: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000688430, 0xc00039c160, 0x2f3fe00, 0xc000557500, 0xc00081fc00)
2020-02-26T15:40:09.572+0530 [DEBUG] plugin.terraform-provider-helm_v1.0.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-helm/vendor/google.golang.org/grpc/server.go:710 +0xbb
2020-02-26T15:40:09.572+0530 [DEBUG] plugin.terraform-provider-helm_v1.0.0_x4: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-02-26T15:40:09.572+0530 [DEBUG] plugin.terraform-provider-helm_v1.0.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-helm/vendor/google.golang.org/grpc/server.go:708 +0xa1
2020-02-26T15:40:09.590+0530 [DEBUG] plugin: plugin process exited: path=/Users/gaurav/.terraform/plugins/darwin_amd64/terraform-provider-helm_v1.0.0_x4 pid=12834 error="exit status 2"
2020/02/26 15:40:09 [ERROR] <root>: eval: *terraform.EvalDiff, err: rpc error: code = Unavailable desc = transport is closing
2020/02/26 15:40:09 [ERROR] <root>: eval: *terraform.EvalDiff, err: rpc error: code = Unavailable desc = transport is closing
2020/02/26 15:40:09 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2020/02/26 15:40:09 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2020/02/26 15:40:09 [TRACE] [walkPlan] Exiting eval tree: helm_release.test_m
2020/02/26 15:40:09 [TRACE] vertex "helm_release.test_m": visit complete
2020/02/26 15:40:09 [TRACE] [walkPlan] Exiting eval tree: helm_release.efs_provisioner
2020/02/26 15:40:09 [TRACE] vertex "helm_release.test_m": dynamic subgraph encountered errors
2020/02/26 15:40:09 [TRACE] vertex "helm_release.efs_provisioner": visit complete
2020/02/26 15:40:09 [TRACE] vertex "helm_release.efs_provisioner": dynamic subgraph encountered errors
2020/02/26 15:40:09 [TRACE] vertex "helm_release.test_m": visit complete
2020/02/26 15:40:09 [TRACE] vertex "helm_release.efs_provisioner": visit complete
2020/02/26 15:40:09 [ERROR] <root>: eval: *terraform.EvalDiff, err: rpc error: code = Unavailable desc = transport is closing
2020/02/26 15:40:09 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2020/02/26 15:40:09 [TRACE] [walkPlan] Exiting eval tree: helm_release.test-m2
2020/02/26 15:40:09 [TRACE] vertex "helm_release.test-m2": visit complete
2020/02/26 15:40:09 [TRACE] vertex "helm_release.test-m2": dynamic subgraph encountered errors
2020/02/26 15:40:09 [TRACE] vertex "helm_release.test-m2": visit complete
2020/02/26 15:40:09 [TRACE] dag/walk: upstream of "kubectl_manifest.test-m2-mappings" errored, so skipping
2020/02/26 15:40:09 [TRACE] dag/walk: upstream of "provider.kubectl (close)" errored, so skipping
2020/02/26 15:40:09 [TRACE] dag/walk: upstream of "provider.helm (close)" errored, so skipping
2020/02/26 15:40:09 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2020/02/26 15:40:09 [TRACE] dag/walk: upstream of "root" errored, so skipping
2020/02/26 15:40:09 [INFO] backend/local: plan operation completed
2020-02-26T15:40:09.605+0530 [DEBUG] plugin: plugin exited
2020-02-26T15:40:09.607+0530 [DEBUG] plugin: plugin process exited: path=/Users/gaurav/.terraform.d/plugins/terraform-provider-kubectl pid=12833
2020-02-26T15:40:09.607+0530 [DEBUG] plugin: plugin exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues
```

### Expected Behavior
Terraform should not crash

### Actual Behavior
Terraform crashed with Segfault

**Comment by gau1991** [comment]
I was able to replicate this issue multiple times and root cause for this issue is, in our current environment we are using [Helm S3 plugin](https://github.com/hypnoglow/helm-s3) to get helm charts. 
Whenever we are referring the URLs starting with S3 protocol with `helm_repository`, the plugin with is crashing with provided crash. 
Although this was working fine with Helm2

**Comment by jrhouston** [comment]
Closing as this should be fixed in the latest version of the provider. Please reopen if this is still an issue.

**Comment by jonrob** [comment]
@jrhouston - seeing extremely similar behavior with the latest provider version used - 2.1.1. 

* Upgraded charts to Helm 3 from Helm 2 using helm 2to3. 
* Upgraded provider version to latest.
* Ran Terraform, fails with `Error: rpc error: code = Unavailable desc = transport is closing`
* HELM_DEBUG=1 TF_LOG=DEBUG output https://gist.github.com/jonrob/d8957fb3604f25972e3809bf4a0232a4.

Terraform version 0.12.21.
Kubernetes version 1.17.
