### ISSUE TITLE
Crash `PANIC: close of nil channel`

### ISSUE THREAD

**Issue by TjeuKayim** [hashicorp/terraform-provider-helm#693]
```txt
PANIC: close of nil channel

goroutine 495 [running]:
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).stop(0xc00011b700)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-helm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/server.go:201 +0x71
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).Stop(0xc00011b700, 0x1ff78e0, 0xc000ec0270, 0xc000ec02a0, 0xc00011b700, 0xc000ec0270, 0xc00035aba0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-helm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/server.go:215 +0xa1
```

### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: v0.15.0-dev (build from commit e9c7f37b8ca9391e8c5c6003da1067c704d530da)
Provider version: v2.0.2
Kubernetes version: EKS 1.18
Helm version: bundled?
```

### Affected Resource(s)

Both provider.terraform-provider-kubernetes and provider.terraform-provider-helm_v2.0.2_x5 paniced at the same time.
See trace log at `2021-03-03T15:16:00.204+0100`

### Debug Output

Recorded with `TF_LOG=TRACE`
https://gist.github.com/TjeuKayim/9ab30b3e0db260cabea69d256a569567#file-trace-log

standard output
https://gist.github.com/TjeuKayim/9ab30b3e0db260cabea69d256a569567#file-stdout-log

### Panic Output

The crash log (from a similar crash last month). 
https://gist.github.com/TjeuKayim/9ab30b3e0db260cabea69d256a569567#file-crash-log

### Steps to Reproduce

1. `terraform destroy`
2. While the Kubernetes/ingress is being deleted for a Kubernetes cluster for which the autoscaling group has already been terminated, it got stuck
3. Press `Ctrl + C`

### Expected Behavior

Stopped gracefully.

### Actual Behavior

The plugin crashed.

### Important Factoids

I have issues in the order of operations when destroying, so that probably caused an edge case that made the plugin crash.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by TjeuKayim** [comment]
This is probably related to <https://github.com/hashicorp/terraform-plugin-go/issues/45>
