### ISSUE TITLE
Provider example fails on TF 0.15.2

### ISSUE THREAD

**Issue by aidan-melen** [hashicorp/terraform-provider-helm#747]
### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: v0.15.2
Provider version: 2.1.2
Kubernetes version: 1.19
```

### Affected Resource(s)

- helm_release
- helm_repository

### Terraform Configuration Files
```hcl
provider "helm" {
  kubernetes {
    config_path = "~/.kube/config"
  }
}

resource "helm_release" "nginx_ingress" {
  name       = "nginx-ingress-controller"

  repository = "https://charts.bitnami.com/bitnami"
  chart      = "nginx-ingress-controller"

  set {
    name  = "service.type"
    value = "ClusterIP"
  }
}
```

### Debug Output

NOTE: In addition to Terraform debugging, please set HELM_DEBUG=1 to enable debugging info from helm.

### Steps to Reproduce

1. `terraform apply`

```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # helm_release.nginx_ingress will be created
  + resource "helm_release" "nginx_ingress" {
      + atomic                     = false
      + chart                      = "nginx-ingress-controller"
      + cleanup_on_fail            = false
      + create_namespace           = false
      + dependency_update          = false
      + disable_crd_hooks          = false
      + disable_openapi_validation = false
      + disable_webhooks           = false
      + force_update               = false
      + id                         = (known after apply)
      + lint                       = false
      + manifest                   = (known after apply)
      + max_history                = 0
      + metadata                   = (known after apply)
      + name                       = "nginx-ingress-controller"
      + namespace                  = "ps-system"
      + recreate_pods              = false
      + render_subchart_notes      = true
      + replace                    = false
      + repository                 = "https://charts.bitnami.com/bitnami"
      + reset_values               = false
      + reuse_values               = false
      + skip_crds                  = false
      + status                     = "deployed"
      + timeout                    = 300
      + verify                     = false
      + version                    = "7.6.6"
      + wait                       = true
      + wait_for_jobs              = false

      + set {
          + name  = "service.type"
          + value = "ClusterIP"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
Failed running command "cd '/terraform' && envdir /env terraform show -json /terraform/terraform.tfplan" (exit 2)
Output:



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.204508447.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.204508447.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
github.com/zclconf/go-cty/cty.Value.GetAttr(0x2c6b4b0, 0xc0013016a0, 0x0, 0x0, 0xc0015387d0, 0xd, 0x0, 0x1, 0x203000, 0x203000)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.8.3/cty/value_ops.go:760 +0x416
github.com/hashicorp/terraform/configs/configschema.(*Block).ValueMarks(0xc001bc9440, 0x2c6b4b0, 0xc0013016a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x40, 0x0, ...)
	/home/circleci/project/project/configs/configschema/marks.go:33 +0x545
github.com/hashicorp/terraform/command/jsonplan.(*plan).marshalResourceChanges(0xc000dd1380, 0xc001812390, 0xc000962120, 0x0, 0x0)
	/home/circleci/project/project/command/jsonplan/plan.go:218 +0x1825
github.com/hashicorp/terraform/command/jsonplan.Marshal(0xc000a225b0, 0xc0005f47e0, 0xc00184b260, 0xc000962120, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/circleci/project/project/command/jsonplan/plan.go:124 +0x23f
github.com/hashicorp/terraform/command.(*ShowCommand).Run(0xc000250fc0, 0xc00004c0b0, 0x1, 0x2, 0xc000442790)
	/home/circleci/project/project/command/show.go:152 +0x966
github.com/mitchellh/cli.(*CLI).Run(0xc000390280, 0xc0003ce0f0, 0x27e9055, 0x4)
	/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x41a
main.wrappedMain(0x0)
	/home/circleci/project/project/main.go:384 +0x1112
main.realMain(0x0)
	/home/circleci/project/project/main.go:115 +0x554
main.main()
	/home/circleci/project/project/main.go:58 +0x25
```

### Expected Behavior

releases the example chart

### Actual Behavior

provider crashed

### References

- GH-1234

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
@aidan-melen I tried the configuration you supplied and was able to successfully apply it on minikube. Can you share more details about the environment where you encountered this? What kind of Kubernetes cluster was involved?

**Comment by aidan-melen** [comment]
@alexsomesan I am using an EKS cluster. You can spin one up quickly with https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/basic/main.tf

**Comment by aidan-melen** [comment]
So this seems to be related to my environment and not the helm chart... My apologies. I was able to deploy the `main.tf` from local state, but it failed in remote state on Terraform Enterprise.

**Comment by aidan-melen** [comment]
So this seems to be related to my environment and not the helm chart... My apologies. I was able to deploy the main.tf from local state, but it failed in remote state on Terraform Enterprise.
