### ISSUE TITLE
Plugin crashes when invalid data passed to cluster_ca_certificate

### ISSUE THREAD

**Issue by aaronmell** [hashicorp/terraform-provider-helm#94]
passing something like this (invalid data)
```
provider "kubernetes" {
cluster_ca_certificate   = "${data.aws_eks_cluster.eks_cluster.certificate_authority}"
}
causes a panic
```

panic: Error reading level config: '' expected type 'string', got unconvertible type '[]interface {}'
2018-07-20T15:06:18.523-0500 [DEBUG] plugin.terraform-provider-helm: 
2018-07-20T15:06:18.523-0500 [DEBUG] plugin.terraform-provider-helm: goroutine 82 [running]:
2018-07-20T15:06:18.523-0500 [DEBUG] plugin.terraform-provider-kubernetes_v1.1.0_x4: panic: Error reading level config: '' expected type 'string', got unconvertible type '[]interface {}'
2018-07-20T15:06:18.523-0500 [DEBUG] plugin.terraform-provider-kubernetes_v1.1.0_x4: 
2018-07-20T15:06:18.523-0500 [DEBUG] plugin.terraform-provider-kubernetes_v1.1.0_x4: goroutine 100 [running]:
2018-07-20T15:06:18.523-0500 [DEBUG] plugin.terraform-provider-kubernetes_v1.1.0_x4: github.com/terraform-providers/terraform-provider-kubernetes/vendor/github.com/hashicorp/terraform/helper/schema.(*ResourceData).get(0xc42021ee00, 0xc4202928a0, 0x1, 0x1, 0xc420292812, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2018-07-20T15:06:18.524-0500 [DEBUG] plugin.terraform-provider-helm: github.com/mcuadros/terraform-provider-helm/vendor/github.com/hashicorp/terraform/helper/schema.(*ResourceData).get(0xc420a45960, 0xc4203db090, 0x1, 0x1, 0xc4203db012, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2018-07-20T15:06:18.524-0500 [DEBUG] plugin.terraform-provider-helm: 	/home/mcuadros/workspace/go/src/github.com/mcuadros/terraform-provider-helm/vendor/github.com/hashicorp/terraform/helper/schema/resource_data.go:508 +0x44b
2018-07-20T15:06:18.524-0500 [DEBUG] plugin.terraform-provider-kubernetes_v1.1.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-kubernetes/vendor/github.com/hashicorp/terraform/helper/schema/resource_data.go:502 +0x4ac
2018-07-20T15:06:18.524-0500 [DEBUG] plugin.terraform-provider-helm: github.com/mcuadros/terraform-provider-helm/vendor/github.com/hashicorp/terraform/helper/schema.(*ResourceData).getChange(0xc420a45960, 0x25b4d97, 0xa, 0x1201, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2018-07-20T15:06:18.524-0500 [DEBUG] plugin.terraform-provider-helm: 	/home/mcuadros/workspace/go/src/github.com/mcuadros/terraform-provider-helm/vendor/github.com/hashicorp/terraform/helper/schema/resource_data.go:479 +0x127
2018-07-20T15:06:18.524-0500 [DEBUG] plugin.terraform-provider-kubernetes_v1.1.0_x4: github.com/terraform-providers/terraform-provider-kubernetes/vendor/github.com/hashicorp/terraform/helper/schema.(*ResourceData).getChange(0xc42021ee00, 0x267b939, 0x16, 0x1201, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2018-07-20T15:06:18.524-0500 [DEBUG] plugin.terraform-provider-kubernetes_v1.1.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-kubernetes/vendor/github.com/hashicorp/terraform/helper/schema/resource_data.go:473 +0x135
2018-07-20T15:06:18.524-0500 [DEBUG] plugin.terraform-provider-kubernetes_v1.1.0_x4: github.com/terraform-providers/terraform-provider-kubernetes/vendor/github.com/hashicorp/terraform/helper/schema.(*ResourceData).diffChange(0xc42021ee00, 0x267b939, 0x16, 0x25c0100, 0x1, 0x80000000000, 0x30, 0x30)
2018-07-20T15:06:18.524-0500 [DEBUG] plugin.terraform-provider-kubernetes_v1.1.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-kubernetes/vendor/github.com/hashicorp/terraform/helper/schema/resource_data.go:450 +0xa5
2018-07-20T15:06:18.524-0500 [DEBUG] plugin.terraform-provider-kubernetes_v1.1.0_x4: github.com/terraform-providers/terraform-provider-kubernetes/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.diffString(0xc4208e4660, 0x267b939, 0x16, 0xc42092a1e0, 0xc4204cd6f0, 0x3383b40, 0xc42021ee00, 0x1029100, 0x0, 0x0)
2018-07-20T15:06:18.524-0500 [DEBUG] plugin.terraform-provider-kubernetes_v1.1.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-kubernetes/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:1158 +0xa0
2018-07-20T15:06:18.524-0500 [DEBUG] plugin.terraform-provider-helm: github.com/mcuadros/terraform-provider-helm/vendor/github.com/hashicorp/terraform/helper/schema.(*ResourceData).diffChange(0xc420a45960, 0x25b4d97, 0xa, 0x0, 0x0, 0x0, 0x180c501, 0xc420a45960)
2018-07-20T15:06:18.524-0500 [DEBUG] plugin.terraform-provider-kubernetes_v1.1.0_x4: github.com/terraform-providers/terraform-provider-kubernetes/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.diff(0xc4208e4660, 0x267b939, 0x16, 0xc42092a1e0, 0xc4205ce7c0, 0x3383b40, 0xc42021ee00, 0xdc60c64efb99a400, 0x0, 0x0)
2018-07-20T15:06:18.524-0500 [DEBUG] plugin.terraform-provider-kubernetes_v1.1.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-kubernetes/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:774 +0x49f
2018-07-20T15:06:18.524-0500 [DEBUG] plugin.terraform-provider-kubernetes_v1.1.0_x4: github.com/terraform-providers/terraform-provider-kubernetes/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.Diff(0xc4208e4660, 0x0, 0xc4203cc2a0, 0x0, 0x0, 0x0, 0xc4205f3b78, 0x10bfd3f, 0x2347340)
2018-07-20T15:06:18.524-0500 [DEBUG] plugin.terraform-provider-kubernetes_v1.1.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-kubernetes/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:424 +0x24a
2018-07-20T15:06:18.524-0500 [DEBUG] plugin.terraform-provider-kubernetes_v1.1.0_x4: github.com/terraform-providers/terraform-provider-kubernetes/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Configure(0xc4208e8d90, 0xc4203cc2a0, 0xc4205ce780, 0xc4205ce7a0)
2018-07-20T15:06:18.524-0500 [DEBUG] plugin.terraform-provider-kubernetes_v1.1.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-kubernetes/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:254 +0x72
2018-07-20T15:06:18.524-0500 [DEBUG] plugin.terraform-provider-helm: 	/home/mcuadros/workspace/go/src/github.com/mcuadros/terraform-provider-helm/vendor/github.com/hashicorp/terraform/helper/schema/resource_data.go:456 +0x97
2018-07-20T15:06:18.524-0500 [DEBUG] plugin.terraform-provider-helm: github.com/mcuadros/terraform-provider-helm/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.diffList(0xc420a840f0, 0x25b4d97, 0xa, 0xc420a86c30, 0xc420a2d708, 0x278d840, 0xc420a45960, 0x1028d00, 0x0, 0x0)
2018-07-20T15:06:18.524-0500 [DEBUG] plugin.terraform-provider-helm: 	/home/mcuadros/workspace/go/src/github.com/mcuadros/terraform-provider-helm/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:806 +0x84
2018-07-20T15:06:18.524-0500 [DEBUG] plugin.terraform-provider-kubernetes_v1.1.0_x4: github.com/terraform-providers/terraform-provider-kubernetes/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Configure(0xc420358b60, 0xc4203cc2a0, 0xc420758180, 0x0, 0x0)
2018-07-20T15:06:18.524-0500 [DEBUG] plugin.terraform-provider-kubernetes_v1.1.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-kubernetes/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:517 +0x42
2018-07-20T15:06:18.524-0500 [DEBUG] plugin.terraform-provider-helm: github.com/mcuadros/terraform-provider-helm/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.diff(0xc420a840f0, 0x25b4d97, 0xa, 0xc420a86c30, 0xc420a8e400, 0x278d840, 0xc420a45960, 0xc42074a900, 0x0, 0x0)
2018-07-20T15:06:18.524-0500 [DEBUG] plugin.terraform-provider-helm: 	/home/mcuadros/workspace/go/src/github.com/mcuadros/terraform-provider-helm/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:776 +0x3c3
2018-07-20T15:06:18.524-0500 [DEBUG] plugin.terraform-provider-helm: github.com/mcuadros/terraform-provider-helm/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.Diff(0xc420a840f0, 0x0, 0xc420a847e0, 0x0, 0x0, 0x0, 0x22412a0, 0xc420a84b01, 0x0)
2018-07-20T15:06:18.524-0500 [DEBUG] plugin.terraform-provider-kubernetes_v1.1.0_x4: reflect.Value.call(0xc4203d6900, 0xc42017a020, 0x13, 0x2665891, 0x4, 0xc4205f3f20, 0x3, 0x3, 0xc4204866d8, 0x1039ddf, ...)
2018-07-20T15:06:18.524-0500 [DEBUG] plugin.terraform-provider-kubernetes_v1.1.0_x4: 	/usr/local/go/src/reflect/value.go:434 +0x905
2018-07-20T15:06:18.524-0500 [DEBUG] plugin.terraform-provider-helm: 	/home/mcuadros/workspace/go/src/github.com/mcuadros/terraform-provider-helm/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:424 +0x211
2018-07-20T15:06:18.524-0500 [DEBUG] plugin.terraform-provider-kubernetes_v1.1.0_x4: reflect.Value.Call(0xc4203d6900, 0xc42017a020, 0x13, 0xc420486720, 0x3, 0x3, 0x0, 0x0, 0x0)
2018-07-20T15:06:18.524-0500 [DEBUG] plugin.terraform-provider-kubernetes_v1.1.0_x4: 	/usr/local/go/src/reflect/value.go:302 +0xa4
2018-07-20T15:06:18.524-0500 [DEBUG] plugin.terraform-provider-helm: github.com/mcuadros/terraform-provider-helm/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Configure(0xc420a44fc0, 0xc420a847e0, 0xc420a8e3c0, 0xc420a8e3e0)
2018-07-20T15:06:18.524-0500 [DEBUG] plugin.terraform-provider-helm: 	/home/mcuadros/workspace/go/src/github.com/mcuadros/terraform-provider-helm/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:254 +0x72
2018-07-20T15:06:18.524-0500 [DEBUG] plugin.terraform-provider-kubernetes_v1.1.0_x4: net/rpc.(*service).call(0xc420742080, 0xc4208ac050, 0xc42088e020, 0xc4205de100, 0xc420358020, 0x255b4a0, 0xc4203cc2a0, 0x16, 0x2347340, 0xc420758180, ...)
2018-07-20T15:06:18.524-0500 [DEBUG] plugin.terraform-provider-helm: github.com/mcuadros/terraform-provider-helm/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Configure(0xc4209e3bc0, 0xc420a847e0, 0xc42000cde0, 0x0, 0x0)
2018-07-20T15:06:18.524-0500 [DEBUG] plugin.terraform-provider-kubernetes_v1.1.0_x4: 	/usr/local/go/src/net/rpc/server.go:381 +0x142
2018-07-20T15:06:18.525-0500 [DEBUG] plugin.terraform-provider-kubernetes_v1.1.0_x4: created by net/rpc.(*Server).ServeCodec
2018-07-20T15:06:18.524-0500 [DEBUG] plugin.terraform-provider-helm: 	/home/mcuadros/workspace/go/src/github.com/mcuadros/terraform-provider-helm/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:517 +0x3e
2018-07-20T15:06:18.525-0500 [DEBUG] plugin.terraform-provider-kubernetes_v1.1.0_x4: 	/usr/local/go/src/net/rpc/server.go:475 +0x36b
2018-07-20T15:06:18.525-0500 [DEBUG] plugin.terraform-provider-helm: reflect.Value.call(0xc420094ba0, 0xc42000cbb0, 0x13, 0x25acc6b, 0x4, 0xc42074af18, 0x3, 0x3, 0xc42004b8c0, 0x20002, ...)
2018-07-20T15:06:18.525-0500 [DEBUG] plugin.terraform-provider-helm: 	/usr/lib/go/src/reflect/value.go:447 +0x969
2018-07-20T15:06:18.525-0500 [DEBUG] plugin.terraform-provider-helm: reflect.Value.Call(0xc420094ba0, 0xc42000cbb0, 0x13, 0xc420a20f18, 0x3, 0x3, 0xc42019d0e0, 0x143318b, 0x1)
2018-07-20T15:06:18.525-0500 [DEBUG] plugin.terraform-provider-helm: 	/usr/lib/go/src/reflect/value.go:308 +0xa4
2018-07-20T15:06:18.525-0500 [DEBUG] plugin.terraform-provider-helm: net/rpc.(*service).call(0xc42091d7c0, 0xc4207876d0, 0xc420a480e0, 0xc420a480f0, 0xc420920980, 0xc4209e3c80, 0x249d8e0, 0xc420a847e0, 0x16, 0x22412a0, ...)
2018-07-20T15:06:18.525-0500 [DEBUG] plugin.terraform-provider-helm: 	/usr/lib/go/src/net/rpc/server.go:384 +0x14e
2018-07-20T15:06:18.525-0500 [DEBUG] plugin.terraform-provider-helm: created by net/rpc.(*Server).ServeCodec
2018-07-20T15:06:18.525-0500 [DEBUG] plugin.terraform-provider-helm: 	/usr/lib/go/src/net/rpc/server.go:480 +0x43a
2018/07/20 15:06:18 [ERROR] root: eval: *terraform.EvalConfigProvider, err: unexpected EOF
2018/07/20 15:06:18 [ERROR] root: eval: *terraform.EvalSequence, err: unexpected EOF
2018/07/20 15:06:18 [ERROR] root: eval: *terraform.EvalOpFilter, err: unexpected EOF
2018/07/20 15:06:18 [ERROR] root: eval: *terraform.EvalSequence, err: unexpected EOF
2018/07/20 15:06:18 [TRACE] [walkRefresh] Exiting eval tree: provider.kubernetes
2018/07/20 15:06:18 [TRACE] dag/walk: upstream errored, not walking "module.infrastructure.kubernetes_namespace.infrastructure"
2018/07/20 15:06:18 [TRACE] dag/walk: upstream errored, not walking "module.infrastructure.kubernetes_storage_class.name"
2018/07/20 15:06:18 [TRACE] dag/walk: upstream errored, not walking "provider.kubernetes (close)"
2018-07-20T15:06:18.528-0500 [DEBUG] plugin: plugin process exited:

**Comment by meyskens** [comment]
```
provider "kubernetes" {
cluster_ca_certificate   = "${data.aws_eks_cluster.eks_cluster.certificate_authority}"
}
```
If this is exactly the line that causes the crash this would be an issue for https://github.com/terraform-providers/terraform-provider-kubernetes
